"""Pydantic models for Habla Hermano database entities.

These models provide type hints and validation for data returned from Supabase.
They replace the previous SQLAlchemy models now that we use Supabase Postgres.
"""

from datetime import datetime

from pydantic import BaseModel, Field


class UserProfile(BaseModel):
    """User profile stored in Supabase."""

    id: str  # UUID from Supabase Auth
    display_name: str | None = None
    preferred_language: str = "es"
    current_level: str = "A1"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class Vocabulary(BaseModel):
    """Vocabulary word learned by a user."""

    id: int | None = None  # Auto-generated by Supabase
    user_id: str  # UUID reference to auth.users
    word: str
    translation: str
    language: str  # 'es' or 'de'
    part_of_speech: str | None = None
    first_seen_at: datetime = Field(default_factory=datetime.utcnow)
    times_seen: int = 1
    times_correct: int = 0

    class Config:
        """Pydantic configuration."""

        from_attributes = True


class LearningSession(BaseModel):
    """Learning session tracking for a user."""

    id: int | None = None  # Auto-generated by Supabase
    user_id: str  # UUID reference to auth.users
    started_at: datetime = Field(default_factory=datetime.utcnow)
    ended_at: datetime | None = None
    language: str  # 'es' or 'de'
    level: str  # A0, A1, A2, B1
    messages_count: int = 0
    words_learned: int = 0

    class Config:
        """Pydantic configuration."""

        from_attributes = True


class LessonProgress(BaseModel):
    """Lesson completion tracking for a user."""

    user_id: str  # UUID reference to auth.users
    lesson_id: str
    completed_at: datetime | None = None
    score: int | None = None

    class Config:
        """Pydantic configuration."""

        from_attributes = True


class Setting(BaseModel):
    """User settings stored per user.

    Note: In the Supabase schema, settings are stored in user_profiles.
    This model is kept for backwards compatibility during migration.
    """

    user_id: str
    key: str
    value: str

    class Config:
        """Pydantic configuration."""

        from_attributes = True
