"""Pydantic models for Habla Hermano database entities.

These models provide type hints and validation for data returned from Supabase.
They replace the previous SQLAlchemy models now that we use Supabase Postgres.
"""

from datetime import UTC, datetime

from pydantic import BaseModel, ConfigDict, Field


class UserProfile(BaseModel):
    """User profile stored in Supabase."""

    id: str  # UUID from Supabase Auth
    display_name: str | None = None
    preferred_language: str = "es"
    current_level: str = "A1"
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class Vocabulary(BaseModel):
    """Vocabulary word learned by a user."""

    model_config = ConfigDict(from_attributes=True)

    id: int | None = None  # Auto-generated by Supabase
    user_id: str  # UUID reference to auth.users
    word: str
    translation: str
    language: str  # 'es' or 'de'
    part_of_speech: str | None = None
    first_seen_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    times_seen: int = 1
    times_correct: int = 0

    # SM-2 spaced repetition fields
    easiness_factor: float = 2.5  # How easy this word is (1.3 - 2.5+)
    interval_days: int = 0  # Current review interval
    repetition_count: int = 0  # Successful reviews in a row
    next_review_at: datetime | None = None  # When due (None = not yet in rotation)
    last_reviewed_at: datetime | None = None


class LearningSession(BaseModel):
    """Learning session tracking for a user."""

    model_config = ConfigDict(from_attributes=True)

    id: int | None = None  # Auto-generated by Supabase
    user_id: str  # UUID reference to auth.users
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    ended_at: datetime | None = None
    language: str  # 'es' or 'de'
    level: str  # A0, A1, A2, B1
    messages_count: int = 0
    words_learned: int = 0


class LessonProgress(BaseModel):
    """Lesson completion tracking for a user."""

    model_config = ConfigDict(from_attributes=True)

    user_id: str  # UUID reference to auth.users
    lesson_id: str
    completed_at: datetime | None = None
    score: int | None = None
